---
title: "Momentum Indicator"
author: "CA"
date: "January 10, 2016"
output: html_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# Setup
setwd("~/Google Drive/TSI/R-Version/GITed Version")

# Packages
library(ggplot2)
library(dplyr)
library(zoo)
library(TTR)
library(lubridate)
library(quantmod)
library(googleVis)

# Markets
markets <- read.csv("markets.csv", as.is = TRUE)

# Dates
to <- Sys.Date()
from <- to-300

stockdata <- new.env()
# Pull data
a <- getSymbols(markets$Ticker, env = stockdata, from = from, to = to)

# Loop over Envirment to compute ratio
par(mar = c(2,2,3,2), mfrow = c(5,3))
TSI <- xts()

for (i in ls(stockdata)){
  
  # pull to tmp
  rm(tmp)
  tmp <- stockdata[[i]]
  
  # Compute TSI Ratio
  tmp$Ratio <- SMA(tmp[,6], n = 25) / SMA(tmp[,6], n = 126)
  
  # Remove NAs
  tmp <- tmp[!is.na(tmp$Ratio)]
  
  # Put back into environment
  stockdata[[i]] <- tmp
  
  # Make a cool overview plot of all markets
  country <- markets %>% filter(Ticker  = grepl(paste(i,"$", sep = ""), Ticker)) %>% select(Country, Ticker)
  country <- as.character(country)
  plot.xts(tmp$Ratio, main = country, ylim = c(.9,1.1), ylab = "TSi", xlab = "MOOOO", ttype = "candles")
  abline(a = 1, b = 0, col = "red")
  
  # Pull last 30 TSIs for each
  TSI <- cbind.xts(TSI,last(tmp$Ratio, 30))

}

# Set TSI ColumnNames
colnames(TSI) <- ls(stockdata)

# Make the rowMeans and remove any non-existing values
TSI$ALL <- rowMeans(TSI, na.rm = TRUE)

# See how many were missing to see how valid the TSI is
TSI$complete <- rowSums(!is.na(TSI))

# Only use if more than 12 markets online
TSI <- TSI[TSI$complete >= 12 ,]

# Since we pull the last 20 values, but not every day is traded everywhere, we
# ended up with far more values, but we're really only interested in the last 20
TSI <- last(TSI, 20)

############################
# Some plotting - will be revised!!
par(mfrow = c(3,1))
plot(TSI$ALL, main = "TSI", ylab = "Ratio")
abline(a = 1, b = 0, col = "red")


plot(TSI$complete, main = "Number of Markets with data available", ylab = "out of 16")

marhier <- as.data.frame(last(TSI)[,1:15])
marhier <- unlist(sort(marhier, decreasing = TRUE))


barplot(marhier, ylim = c(0.9,1.1))
abline(a = 1, b = 0, col = "red")

signal <- ifelse(last(TSI$ALL < 1), "verkaufen/neutral", "accumulate")
slope <- ifelse(as.numeric(last(TSI$ALL,2)[2]) / as.numeric(last(TSI$ALL,2)[1]) >= 1, "steigend", "fallend")

```

## TSI

Report vom `r Sys.Date()`

* TSI - Wert `r last(TSI$ALL)`
* Signal `r signal`
* Bester Markt `r marhier[1]`: `r names(marhier)[1]`
* Veraenderung: TSI is `r slope` 

### TSI MAP

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
op <- options(gvis.plot.tag='chart')
a <- last(TSI)
b <- data.frame(t(a), Name = names(a))
c <- merge(b, markets, by.x = "Name", by.y = "ActualTicker")
colnames(c)[2] <- "TSI"
c <- c[complete.cases(c),]
c <- c %>% group_by(Country) %>% summarise(TSI = mean(TSI))
```
```{r, echo = FALSE, results = 'asis'} 
g <- gvisGeoChart(c, locationvar = "Country", colorvar = "TSI",
                  options = list(
                    width = 800,
                    height = 600,
                    colors = "['red','orange','yellow']"
                  ))
plot(g)
```



